[Settings]
; Hotkey to toggle menu (Default: F5)
MenuKey=F5
ActiveLocation=Michael's Pool
; Global activation state (Default: false)
Enabled=false
RestDuration=30
SwimDuration=45

[Location:Michael's Pool]
CenterX=-811.230
CenterY=175.450
CenterZ=71.850
Radius=18.0
SwimChance=25
RestDuration=30
SwimDuration=45
